version: '3.3'
services:
  db:
    image: postgres:13
    volumes:
      - ${DB_STORAGE}:/var/lib/postgresql/data
      - ${DB_BACKUPS}:/var/lib/backups
    env_file: .postgres.env
    ports:
      - "35432:5432"
  pgadmin:
    image: dpage/pgadmin4
    env_file: ./.pga.env
    volumes:
      - ${PGA_STORAGE}:/var/lib/pgadmin
    ports:
      - "8080:80"
  redis-server:
    image: redis
    ports:
      - "6002:6379"
  app:
    depends_on:
      - db
    build:
      context: ${APP_STORAGE}
      dockerfile: Dockerfile
    volumes:
      - ${APP_STORAGE}:/var/www/
      - ./php.ini:/usr/local/etc/php/php.ini
#    env_file: .app.env
  nginx:
    depends_on:
      - db
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ${APP_STORAGE}/public:/var/www/public

